<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CBT-025" name="Testff" tests="2" failures="1" timestamp="17 Jul 2016 09:42:44 GMT" time="16.729" errors="0">
  <testcase name="DemoGoogle" time="0.016" classname="googleDemo.DemoB">
    <failure type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at googleDemo.DemoB.DemoGoogle(DemoB.java:22)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	... 24 more
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- DemoGoogle -->
  <testcase name="DemoGoogle" time="16.683" classname="googleDemo.GoogleDemo"/>
</testsuite> <!-- Testff -->
